#!/bin/bash

# Variables
GITLAB_URL="https://gitlab.com/username/repo.git"
GITHUB_URL="https://github.com/username/repo.git"
GITLAB_TOKEN="your_gitlab_access_token"
GITHUB_TOKEN="your_github_access_token"

# Clone the GitLab repository
git clone --mirror "$GITLAB_URL"
cd repo.git

# Remove GitLab remote
git remote remove origin

# Add GitHub remote
git remote add origin "https://$GITHUB_TOKEN@github.com/username/repo.git"

# Push all branches and tags to GitHub
git push --mirror

# Cleanup
cd ..
rm -rf repo.git

echo "Migration completed successfully!"
